from dlt.common.normalizers.naming.snake_case import NamingConvention as SnakeCaseNamingConvention

# Reserved keywords in Apache Doris that cannot be used as identifiers without quoting.
# Reference: https://doris.apache.org/docs/dev/sql-manual/sql-reference/sql-statements/keywords
KEYWORDS = {
    "ADD",
    "ALL",
    "ALTER",
    "ANALYZE",
    "AND",
    "ARRAY",
    "AS",
    "ASC",
    "BETWEEN",
    "BIGINT",
    "BITMAP",
    "BOTH",
    "BY",
    "CASE",
    "CHAR",
    "CHARACTER",
    "CHECK",
    "COLLATE",
    "COLUMN",
    "CONVERT",
    "CREATE",
    "CROSS",
    "CUBE",
    "CURRENT_DATE",
    "CURRENT_TIME",
    "CURRENT_TIMESTAMP",
    "CURRENT_USER",
    "DATABASE",
    "DATABASES",
    "DECIMAL",
    "DECIMALV3",
    "DEFAULT",
    "DELETE",
    "DENSE_RANK",
    "DESC",
    "DESCRIBE",
    "DISTINCT",
    "DOUBLE",
    "DROP",
    "DUAL",
    "ELSE",
    "EXCEPT",
    "EXISTS",
    "EXPLAIN",
    "FALSE",
    "FIRST_VALUE",
    "FLOAT",
    "FOR",
    "FORCE",
    "FROM",
    "FULL",
    "FUNCTION",
    "GRANT",
    "GROUP",
    "GROUPS",
    "GROUPING",
    "HAVING",
    "HLL",
    "IF",
    "IGNORE",
    "IN",
    "INDEX",
    "INFILE",
    "INNER",
    "INSERT",
    "INT",
    "INTEGER",
    "INTERSECT",
    "INTO",
    "IS",
    "JOIN",
    "JSON",
    "KEY",
    "KEYS",
    "KILL",
    "LAG",
    "LARGEINT",
    "LAST_VALUE",
    "LATERAL",
    "LEAD",
    "LEFT",
    "LIKE",
    "LIMIT",
    "LOAD",
    "LOCALTIME",
    "LOCALTIMESTAMP",
    "MAXVALUE",
    "MINUS",
    "MOD",
    "NOT",
    "NTILE",
    "NULL",
    "ON",
    "OR",
    "ORDER",
    "OUTER",
    "OUTFILE",
    "OVER",
    "PARTITION",
    "PERCENTILE",
    "PRIMARY",
    "PROCEDURE",
    "RANGE",
    "RANK",
    "READ",
    "REGEXP",
    "RELEASE",
    "RENAME",
    "REPLACE",
    "REVOKE",
    "RIGHT",
    "RLIKE",
    "ROW",
    "ROWS",
    "ROW_NUMBER",
    "SCHEMA",
    "SCHEMAS",
    "SELECT",
    "SET",
    "SHOW",
    "SMALLINT",
    "STRING",
    "TABLE",
    "TERMINATED",
    "TEXT",
    "THEN",
    "TINYINT",
    "TO",
    "TRUE",
    "UNION",
    "UNIQUE",
    "UPDATE",
    "USE",
    "USING",
    "VALUES",
    "VARCHAR",
    "WHEN",
    "WHERE",
    "WITH",
}


class NamingConvention(SnakeCaseNamingConvention):
    def normalize_identifier(self, identifier: str) -> str:
        # If it already ends with _, and the part before it is a keyword,
        # we assume it's already normalized and return it as is to prevent
        # SnakeCaseNamingConvention from turning trailing _ into x (schemax).
        if identifier.endswith("_") and identifier[:-1].upper() in KEYWORDS:
            return identifier

        normalized = super().normalize_identifier(identifier)
        if normalized.upper() in KEYWORDS:
            normalized += "_"

        return normalized
